shortener/short/urls.py
from django.urls import path

from . import views

app_name = 'short'

urlpatterns = [
    path('', views.ShortenerView.as_view(), name='makeshort'),
    path('url/<slug:short>/', views.RedirectUrl.as_view(), name='redirect')
]

shortener/shortener/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('short.urls', namespace='short')),
    path('admin/', admin.site.urls),
]

shortener/short/models.py
from django.db import models

from .services import shortmaker


class Link(models.Model):
    url = models.URLField(unique=True)
    shorturl = models.CharField(unique=True, max_length=8)
    date = models.DateTimeField(auto_now_add=True)
    count = models.PositiveIntegerField(default=0)

    @classmethod
    def create(cls, link):
        short = shortmaker()
        try:
            obj = cls.objects.create(url=link, shorturl=short)
        except Exception:
            obj = cls.objects.get(url=link)
        return obj

shortener/short/forms.py
from django.forms import ModelForm

from .models import Link


class ShortForm(ModelForm):
    class Meta:
        model = Link
        fields = ('url',)

shortener/short/views.py
from django.shortcuts import redirect, render
from django.views import View

from .forms import ShortForm
from .models import Link


class ShortenerView(View):

    def get(self, request, *args, **kwargs):
        form = ShortForm()
        context = {
            'form': form
        }
        return render(request, 'shortener.html', context)

    def post(self, request, *args, **kwargs):
        form = ShortForm(request.POST)
        if not form.is_valid():
            return render(request, 'shortener.html', {'form': form})
        else:
            url = request.POST.get('url', None)
            obj = Link.create(link=url)
            obj.save()
            context = {
                    'form': form,
                    'url': obj.url,
                    'shorturl': request.get_host() + '/url/' + obj.shorturl
                }
            return render(request, 'shortener.html', context)


class RedirectUrl(View):

    def get(self, request, *args, **kwargs):
        link = Link.objects.get(shorturl=kwargs['short'])
        link.count += 1
        link.save()
        return redirect(link.url)

shortener/templates/shortener.html
<html>
  <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Url Shortener</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
      <div style='margin-top: 15%; margin-left: 40%; margin-right: 40%;'>
        <h1><a href="{% url 'short:makeshort' %}" style="text-decoration:none">Главная</a></h1>
        <form action='' method='POST'>
        {% csrf_token %}
        {{ form.as_p}}
        <button>Submit</button>
        </form>
        <h5>Ваша ссылка</h5><p>{{ url }}</p>
        <h5>Ваша короткая ссылка</h5><p>{{ shorturl }}</p>
      </div>

  </body>
</html>